name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          npm install
      - name: Build project
        working-directory: ./frontend
        run: |
          npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./frontend/build
          name: build-files

