name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '12.22.9'
    - name: Install Dependencies
      working-directory: ./frontend
      run: |
        npm install
    - name: Build
      working-directory: ./frontend
      run: |
        npm run build
    - name: Run Tests
      working-directory: ./frontend
      run: |
        npm run test
