name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    needs: test
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install Dependencies
      working-directory: ./frontend
      run: |
        npm install
    - name: Lint
      working-directory: ./frontend
      run: |
        npm run lint

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install Dependencies
      working-directory: ./frontend
      run: |
        npm install
    - name: Run Tests
      working-directory: ./frontend
      run: |
        npm run test

  build:
    needs: lint
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12.22.9, 14, 16, 20]
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          npm install
      - name: Run Build
        working-directory: ./frontend
        run: |
          npm run build
